#!/bin/bash
readonly CONFIG_DAYS="10000"
readonly CONFIG_DEFAULT_BITS="4096"
readonly CONFIG_DEFAULT_MD="sha512"
readonly CONFIG_DN_COUNTRY="US"
readonly CONFIG_DN_ORG="Org"
readonly CONFIG_DN_COMMON_NAME="example.com"
readonly CONFIG_DN_CA_COMMON_NAME="example CA"
readonly CONFIG_SAN="DNS:${CONFIG_DN_COMMON_NAME}, IP:127.0.0.1, IP:192.168.0.2"
